name: Varredura Diaria
on:
  schedule:
    - cron: '0 10 * * *' # Corre às 10h da manhã
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install pandas numpy scipy requests
      - run: python main.py
